### ISSUE TITLE
Admin, Strict Mode, PHP error, DPU_PLUGIN_CHECK not defined

### ISSUE THREAD

**Issue by torvista** [mc12345678/Dynamic_Price_Updater#18]
Set strict error reporting, on an admin page refresh:

> [22-Apr-2019 19:55:14 Europe/Madrid] Request URI: /tienda-156/admin1/index.php, IP address: 127.0.0.1
#1  constant() called at [...\public_html\tienda-156\admin1\includes\init_includes\init_dpu_config.php:114]
#2  require(...\public_html\tienda-156\admin1\includes\init_includes\init_dpu_config.php) called at [...\public_html\tienda-156\includes\autoload_func.php:49]
#3  require(...\public_html\tienda-156\includes\autoload_func.php) called at [...\public_html\tienda-156\admin1\includes\application_top.php:180]
#4  require(...\public_html\tienda-156\admin1\includes\application_top.php) called at [...\public_html\tienda-156\admin1\index.php:10]
--> PHP Warning: constant(): Couldn't find constant DPU_PLUGIN_CHECK in ...\public_html\tienda-156\admin1\includes\init_includes\init_dpu_config.php on line 114.

**Comment by mc12345678** [comment]
To confirm conditions, was the plugin ever considered to have been previously installed to the database in question?

As I understand the report of the issue, a brand new Zen Cart database and fileset were used with no history of DPU being installed. The fileset was applied, and the admin page was then navigated prompting the error.  If this is the case, then the methodology of installation seems to need a drastic revision.

If, however, DPU had previously been installed, but before the implementation of using DPU_VERSION_CHECK, then a separate/different modification is needed to ensure that the variable is defined in the database as it currently is only pushed to the database during initial/new installation. In this case, the problem can be overcome (though by removing the existing settings) by applying the uninstall_dpu.sql found in `admin/includes/installers/dpu` and then reattempting installation/upgrade.

**Comment by torvista** [comment]
It is ok on a new install. When I had checked (too quickly) the installation scripts I did not find the DPU_VERSION_CHECK as it is not defined as a complete name so thought it was missing.
My real db only has 9 of the current 15 constants so yes, needs a re-install.
